# ============================================================
#  Secret con TODAS las credenciales.
#  Esto es una PLANTILLA
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: rp-secrets
  namespace: rp-travels
type: Opaque
stringData:
  # --- Usadas por el contenedor MySQL ---
  MYSQL_ROOT_PASSWORD: "cambia_root"
  MYSQL_DATABASE: "rp_travels"
  MYSQL_USER: "rp_app"
  MYSQL_PASSWORD: "App_RP_2026!"
  # --- Usadas por la aplicación PHP ---
  DB_HOST: "rp-db"          # nombre del Service de MySQL
  DB_USER: "rp_app"
  DB_PASS: "App_RP_2026!"
  DB_NAME: "rp_travels"
  # --- Correo saliente ---
  MAIL_USER: "tu_correo@gmail.com"
  MAIL_PASS: "xxxx xxxx xxxx xxxx"
